command! NosetestFile call vim_python_test_runner#RunDesiredTests("nose_file")
command! NosetestClass call vim_python_test_runner#RunDesiredTests("nose_class")
command! NosetestMethod call vim_python_test_runner#RunDesiredTests("nose_method")
command! NosetestBaseMethod call vim_python_test_runner#RunDesiredTests("nose_base_method")
command! RerunLastTests call vim_python_test_runner#RunDesiredTests("rerun")
